version: "3.2"
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE      : payment
      MYSQL_USER          : user
      MYSQL_PASSWORD      : 1234