spring:
  profiles:
    active: local
---
spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:////sample
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db-init/schema.sql
#      data-locations: classpath:db-init/data.sql
server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
  port: 8080
  tomcat:
    threads:
      max: 2000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    dev.fastcampus: debug
---
spring:
  config:
    activate:
      on-profile: stress
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: 1234
    hikari:
      connection-timeout: 300_000
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect