spring:
  application:
    name: virtual-thread
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    username: user
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: false
logging:
  level:
    dev.fastcampus: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
api:
  externalUrl: http://localhost:8081