spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      fetch-max-wait: 5s
    listener:
      immediate-stop: false
      poll-timeout: 10s
    properties:
      spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    dev.fastcampus.kafka: debug
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"
payment:
  kafka:
    topic: PURCHASE
---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

